title: "Young Lab"
description: "Engineering biology to make catalysts and sensors for a sustainable future. Worcester Polytechnic Institute."
url: "https://ericmyoung.com"
baseurl: ""

markdown: kramdown
permalink: pretty
future: true

collections:
  projects:
    output: true
    permalink: /projects/:name/

# GitHub Pages safe default (no custom plugins)
plugins: []