title: "Young Lab"
description: "Engineering biology to make catalysts and sensors for a sustainable future. Worcester Polytechnic Institute."
url: "https://emyounglab.github.io"
baseurl: ""

markdown: kramdown
permalink: pretty
future: true

# GitHub Pages safe default (no custom plugins)
plugins: []