title: "Young Lab"
description: "We develop methods and tools for X, Y, and Z."
url: ""
baseurl: "younglab_website"   # set to "/repo-name" if your site is username.github.io/repo-name

markdown: kramdown
permalink: pretty

# GitHub Pages safe default (no custom plugins)
plugins: []